src/LeapYearApp.Web/Models/ViewModels/Login.cs
namespace LeapYearApp.Models.ViewModels
{
    public class Login
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

src/LeapYearApp.Web/Models/ViewModels/Register.cs
namespace LeapYearApp.Models.ViewModels
{
    public class Register
    {
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

src/LeapYearApp.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace LeapYearApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/LeapYearApp.Web/Pages/Index.cshtml.cs
using LeapYearApp.Data;
using LeapYearApp.Models.Domain;
using LeapYearApp.Models.ViewModels;
using LeapYearApp.Repositories;
using LeapYearApp.Web.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration.UserSecrets;
using System.Security.Claims;

namespace LeapYearApp.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public AddYearNameForm AddYearNameFormRequest { get; set; }

        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IMessageService _messageService;
        private readonly ILogger<IndexModel> _logger;
        private readonly IYearNameFormRepository _yearNameFormRepository;

        public IndexModel(ILogger<IndexModel> logger, IYearNameFormRepository yearNameFormRepository, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, IMessageService messageService)
        {
            _logger = logger;
            _yearNameFormRepository = yearNameFormRepository;
            _userManager = userManager;
            _signInManager = signInManager;
            _messageService = messageService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            AddYearNameFormRequest.PublishedDate = DateTime.Now;

            bool isFemale = false;
            if (AddYearNameFormRequest.Name != null)
            {
                isFemale = AddYearNameFormRequest.Name.ToLower().EndsWith('a');
            }

            bool isUserSignedIn = _signInManager.IsSignedIn(User);

            Guid userId = Guid.Empty;
            string username = "Anonymous";

            if (isUserSignedIn)
            {
                userId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                IdentityUser user = await _userManager.FindByIdAsync(userId.ToString());
                username = user.UserName;
            }

            var yearNameForm = new YearNameForm()
            {
                Year = AddYearNameFormRequest.Year,
                Name = AddYearNameFormRequest.Name,
                PublishedDate = AddYearNameFormRequest.PublishedDate,
                IsLeapYear = DateTime.IsLeapYear(AddYearNameFormRequest.Year),
                IsFemale = isFemale,
                UserId = userId,
                Login = username
            };


            await _yearNameFormRepository.AddAsync(yearNameForm);

            ViewData["MessageDescription"] = _messageService.GenerateMessageForIndexPage(
                yearNameForm.Year,
                yearNameForm.Name,
                isFemale,
                yearNameForm.IsLeapYear
            );

            return Page();
        }
    }
}

src/LeapYearApp.Web/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LeapYearApp.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }
        public async Task<IActionResult> OnGet()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("Index");
        }
    }
}

src/LeapYearApp.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LeapYearApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/LeapYearApp.Web/Pages/SearchHistory.cshtml.cs
using LeapYearApp.Data;
using LeapYearApp.Extensions;
using LeapYearApp.Models.Domain;
using LeapYearApp.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Security.Claims;

namespace LeapYearApp.Pages
{
    public class SearchHistoryModel : PageModel
    {
        private readonly LeapYearAppDbContext _leapYearAppDbContext;
        private readonly IConfiguration _configuration;
        private readonly IYearNameFormRepository _yearNameFormRepository;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;

        public PaginatedList<YearNameForm> YearNameForms { get; set; }

        public SearchHistoryModel(LeapYearAppDbContext leapYearAppDbContext, IConfiguration configuration, IYearNameFormRepository yearNameFormRepository, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _leapYearAppDbContext = leapYearAppDbContext;
            _configuration = configuration;
            _yearNameFormRepository = yearNameFormRepository;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task OnGetAsync(int? pageIndex)
        {
            IQueryable<YearNameForm> yearNameFormsIQ = from s in _leapYearAppDbContext.YearNameForms
                                                       select s;

            yearNameFormsIQ = yearNameFormsIQ.OrderByDescending(s => s.PublishedDate);

            int pageSize = _configuration.GetValue<int>("PageSize");
            YearNameForms = await PaginatedList<YearNameForm>.CreateAsync(
                               yearNameFormsIQ.AsNoTracking(), pageIndex ?? 1, pageSize);
        }

        public async Task<IActionResult> OnPostDelete(Guid id)
        {
            var yearNameForm = await _yearNameFormRepository.GetByIdAsync(id);

            bool isUserSignedIn = _signInManager.IsSignedIn(User);

            if (!isUserSignedIn)
            {
                return RedirectToPage("SearchHistory");
            }
            else
            {
                Guid userId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                IdentityUser user = await _userManager.FindByIdAsync(userId.ToString());
                if (yearNameForm.UserId == userId && yearNameForm.Login == user.UserName)
                {
                    var deleted = await _yearNameFormRepository.DeleteAsync(id);

                    if (deleted)
                    {
                        return RedirectToPage("SearchHistory");
                    }
                }
            }
            return RedirectToPage("SearchHistory");
        }
    }
}

src/LeapYearApp.Web/Pages/EditYearNameFormRequest.cshtml
@page "{id:Guid}"
@model LeapYearApp.Pages.EditYearNameFormRequestModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-3">
    <div class="container">
        <h3>Wypełnij pola i naciśnij przycisk "Zatwierdź" aby zmienić dane :)</h3>
    </div>
</div>

@if (Model.YearNameForm != null)
{
    <div class="container">
        <form method="post">
            <div class="mb-3">
                <label for="id" class="form-label">Id</label>
                <input type="text" class="form-control" id="id" asp-for="YearNameForm.Id" readonly>
            </div>

            <div class="form-group" mb-2>
                <label for="Name">Imię</label>
                <input type="text" class="form-control" id="name" aria-describedby="NameHelp" placeholder="Wprowadź imię." asp-for="YearNameForm.Name">
                <small id="NameHelp" class="form-text text-muted">Imię nie jest obowiązkowe ;)</small>
            </div>

            <div class="form-group" mb-4>
                <label for="Year">Rok</label>
                <input type="number" class="form-control" id="year" aria-describedby="YearHelp" placeholder="Wprowadź rok." asp-for="YearNameForm.Year">
                <small id="YearHelp" class="form-text text-muted">Zakres: 1899-2022.</small>
            </div>

            <div class="d-grid gap-2" mb-2>
                <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Zatwierdź</button>
            </div>
        </form>
    </div>
}
else
{
    <div class="container">
        <p>Form request not found :(</p>
    </div>
}

src/LeapYearApp.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="bg-secondary bg-opacity-10 py-2 mb-3">
    <div class="container">
        <h3>Wypełnij pola i naciśnij przycisk "Zatwierdź" aby sprawdzić czy podany rok jest przestępny :)</h3>
    </div>
</div>

<div class="container">
    <form method="post">
        <div class="form-group" mb-2>
            <label for="Name">Imię</label>
            <input type="text" class="form-control" id="name" aria-describedby="NameHelp" placeholder="Wprowadź imię." asp-for="AddYearNameFormRequest.Name">
            <small id="NameHelp" class="form-text text-muted">
                Imię nie jest obowiązkowe ;)
            </small>
            <span asp-validation-for="AddYearNameFormRequest.Name" class="text-danger"></span>
        </div>

        <div class="form-group" mb-4>
            <label for="Year">Rok</label>
            <input type="number" class="form-control" id="year" aria-describedby="YearHelp" placeholder="Wprowadź rok." asp-for="AddYearNameFormRequest.Year">
            <small id="YearHelp" class="form-text text-muted">Zakres: 1899-2022.</small>
            <span asp-validation-for="AddYearNameFormRequest.Year" class="text-danger"></span>
        </div>

        <div class="d-grid gap-2" mb-5>
            <button class="btn btn-primary" type="submit">Zatwierdź</button>
        </div>
    </form>
</div>

@{
    var messageDescription = (string)ViewData["MessageDescription"];
}

@if (!string.IsNullOrWhiteSpace(messageDescription))
{
    <div class="container">
        <div class="alert alert-success alert-dismissible" mb-5 role="alert">
            @Html.Raw(messageDescription)
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
}

src/LeapYearApp.Web/Pages/Login.cshtml
@page
@model LeapYearApp.Pages.LoginModel
@{
}

<div class="container mx-auto">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <h1 class="mb-3 mt-5 h3">Logowanie</h1>
            <form method="post">
                <div class="mb-3">
                    <label class="form-label">Nazwa użytkownika</label>
                    <input type="text" class="form-control" asp-for="LoginViewModel.Username"/>
                </div>

                <div class="mb-3">
                    <label class="form-label">Hasło użytkownika</label>
                    <input type="password" class="form-control" asp-for="LoginViewModel.Password"/>
                </div>

                <div class="mb-3">
                    <button type="submit">Zaloguj</button> 
                </div>
            </form>
        </div>
    </div>
</div>

@{
    var messageDescription = (string)ViewData["Notification"];
}

@if (!string.IsNullOrWhiteSpace(messageDescription))
{
    <div class="container">
        <div class="alert alert-danger alert-dismissible" mb-5 role="alert">
            @Html.Raw(messageDescription)
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
}

src/LeapYearApp.Web/Pages/Logout.cshtml
@page
@model LeapYearApp.Pages.LogoutModel
@{
}

src/LeapYearApp.Web/Pages/Register.cshtml
@page
@model LeapYearApp.Pages.RegisterModel
@{
}

<div class="container mx-auto">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <h1 class="mb-3 mt-5 h3">Rejestracja</h1>
            <form method="post">
                <div class="mb-3">
                    <label class="form-label">Nazwa użytkownika</label>
                    <input type="text" class="form-control" asp-for="RegisterViewModel.Username"/>
                </div>

                <div class="mb-3">
                    <label class="form-label">Adres email</label>
                    <input type="email" class="form-control" asp-for="RegisterViewModel.Email"/>
                </div>

                <div class="mb-3">
                    <label class="form-label">Hasło użytkownika</label>
                    <input type="password" class="form-control" asp-for="RegisterViewModel.Password"/>
                </div>

                <div class="mb-3">
                    <button type="submit">Zarejestruj</button> 
                </div>
            </form>
        </div>
    </div>
</div>

@{
    var messageDescription = (string)ViewData["Notification"];
}

@if (!string.IsNullOrWhiteSpace(messageDescription))
{
    <div class="container">
        <div class="alert alert-success alert-dismissible" mb-5 role="alert">
            @Html.Raw(messageDescription)
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
}
```

src/LeapYearApp.Web/Pages/SearchHistory.cshtml
@page
@model LeapYearApp.Pages.SearchHistoryModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-3">
    <div class="container">
        <h1>Historia wyszukiwań</h1>
    </div>
</div>

@if (Model.YearNameForms != null && Model.YearNameForms.Any())
{
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Login</th>
                    <th scope="col" class="text-center">UserID</th>
                    <th scope="col" class="text-center">Imię</th>
                    <th scope="col" class="text-center">Rok</th>
                    <th scope="col" class="text-center">Czy przestępny?</th>
                    <th scope="col" class="text-center">Data wyszukania</th>
                    <th scope="col" class="text-center">Edycja</th>
                    <th scope="col" class="text-center">Usunięcie</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.YearNameForms)
                {
                    <tr>
                        <td class="text-center">@item.Login</td>
                        <td class="text-center">@item.UserId</td>
                        <td class="text-center">@item.Name</td>
                        <td class="text-center">@item.Year</td>
                        <td class="text-center">@((item.IsLeapYear) ? "Tak" : "Nie")</td>
                        <td class="text-center">@item.PublishedDate</td>
                        <td class="text-center"><a href="/EditYearNameFormRequest/@item.Id" class="btn btn-primary">Edit</a></td>
                        <td class="text-center">
                            <form asp-page-handler="Delete" method="post">
                                <input type="hidden" name="id" value="@item.Id" />
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        @{
            var prevDisabled = !Model.YearNameForms.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.YearNameForms.HasNextPage ? "disabled" : "";
        }

        <a asp-page="./SearchHistory"
       asp-route-pageIndex="@(Model.YearNameForms.PageIndex - 1)"
       class="btn btn-primary @prevDisabled">
            Previous
        </a>
        <a asp-page="./SearchHistory"
       asp-route-pageIndex="@(Model.YearNameForms.PageIndex + 1)"
       class="btn btn-primary @nextDisabled">
            Next
        </a>
    </div>
}
else
{
    <div class="container">
        <p>Lista jest pusta :(</p>
    </div>
}